// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _MicroserviceTemplate_.EF.SqlServer;

#nullable disable

namespace _MicroserviceTemplate_.EF.SqlServer.Migrations
{
    [DbContext(typeof(_MicroserviceTemplate_DbContext))]
    partial class _MicroserviceTemplate_DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_MicroserviceTemplate_.Domain.MyTables.MyTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MyTableId");

                    b.Property<DateTime>("CreateTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MyTables", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c209d3b5-6482-439a-be59-3471c170cae9"),
                            CreateTimeUtc = new DateTime(2024, 12, 17, 18, 54, 9, 216, DateTimeKind.Utc).AddTicks(5140),
                            Description = "Add a new record.",
                            UpdateTimeUtc = new DateTime(2024, 12, 17, 18, 54, 9, 216, DateTimeKind.Utc).AddTicks(5140),
                            Value = "Add"
                        },
                        new
                        {
                            Id = new Guid("e5ecdbee-834f-42e7-a25d-b0aa00d3fcf1"),
                            CreateTimeUtc = new DateTime(2024, 12, 17, 18, 54, 9, 216, DateTimeKind.Utc).AddTicks(5140),
                            Description = "Edit existing record.",
                            UpdateTimeUtc = new DateTime(2024, 12, 17, 18, 54, 9, 216, DateTimeKind.Utc).AddTicks(5140),
                            Value = "Edit"
                        },
                        new
                        {
                            Id = new Guid("8ec418ae-69cf-44f0-a1f3-ba26142b3563"),
                            CreateTimeUtc = new DateTime(2024, 12, 17, 18, 54, 9, 216, DateTimeKind.Utc).AddTicks(5150),
                            Description = "Remove existing record.",
                            UpdateTimeUtc = new DateTime(2024, 12, 17, 18, 54, 9, 216, DateTimeKind.Utc).AddTicks(5150),
                            Value = "Remove"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
