// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using _MicroserviceTemplate_.EF;

#nullable disable

namespace _MicroserviceTemplate_.EF.Migrations
{
    [DbContext(typeof(_MicroserviceTemplate_DbContext))]
    [Migration("20241202133609_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("_MicroserviceTemplate_.Domain.MyTables.MyTable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("MyTableId");

                    b.Property<DateTime>("CreateTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MyTables", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c209d3b5-6482-439a-be59-3471c170cae9"),
                            CreateTimeUtc = new DateTime(2024, 12, 2, 13, 36, 9, 545, DateTimeKind.Utc).AddTicks(8217),
                            Description = "Add a new record.",
                            UpdateTimeUtc = new DateTime(2024, 12, 2, 13, 36, 9, 545, DateTimeKind.Utc).AddTicks(8217),
                            Value = "Add"
                        },
                        new
                        {
                            Id = new Guid("e5ecdbee-834f-42e7-a25d-b0aa00d3fcf1"),
                            CreateTimeUtc = new DateTime(2024, 12, 2, 13, 36, 9, 545, DateTimeKind.Utc).AddTicks(8223),
                            Description = "Edit existing record.",
                            UpdateTimeUtc = new DateTime(2024, 12, 2, 13, 36, 9, 545, DateTimeKind.Utc).AddTicks(8223),
                            Value = "Edit"
                        },
                        new
                        {
                            Id = new Guid("8ec418ae-69cf-44f0-a1f3-ba26142b3563"),
                            CreateTimeUtc = new DateTime(2024, 12, 2, 13, 36, 9, 545, DateTimeKind.Utc).AddTicks(8224),
                            Description = "Remove existing record.",
                            UpdateTimeUtc = new DateTime(2024, 12, 2, 13, 36, 9, 545, DateTimeKind.Utc).AddTicks(8224),
                            Value = "Remove"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
