// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _MicroserviceTemplate_.EF;

#nullable disable

namespace _MicroserviceTemplate_.EF.Migrations
{
    [DbContext(typeof(_MicroserviceTemplate_DbContext))]
    [Migration("20241113143045_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_MicroserviceTemplate_.Domain.MyTables.MyTable", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("MyTableId");

                    b.Property<DateTime>("CreateTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTimeUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MyTables", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "Operation:Add",
                            CreateTimeUtc = new DateTime(2024, 11, 13, 14, 30, 44, 687, DateTimeKind.Utc).AddTicks(2282),
                            Description = "Add a new record.",
                            UpdateTimeUtc = new DateTime(2024, 11, 13, 14, 30, 44, 687, DateTimeKind.Utc).AddTicks(2282),
                            Value = "Add"
                        },
                        new
                        {
                            Id = "Operation:Edit",
                            CreateTimeUtc = new DateTime(2024, 11, 13, 14, 30, 44, 687, DateTimeKind.Utc).AddTicks(2286),
                            Description = "Edit existing record.",
                            UpdateTimeUtc = new DateTime(2024, 11, 13, 14, 30, 44, 687, DateTimeKind.Utc).AddTicks(2286),
                            Value = "Edit"
                        },
                        new
                        {
                            Id = "Operation:Remove",
                            CreateTimeUtc = new DateTime(2024, 11, 13, 14, 30, 44, 687, DateTimeKind.Utc).AddTicks(2287),
                            Description = "Remove existing record.",
                            UpdateTimeUtc = new DateTime(2024, 11, 13, 14, 30, 44, 687, DateTimeKind.Utc).AddTicks(2287),
                            Value = "Remove"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
